name: Build & release wheels

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - test-s390x

jobs:
  collect-charms:
    name: Collect charms
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install CLI
        run: pipx install ./cli/
      - name: Collect charms to build from charms.json
        id: collect
        run: collect-charms
    outputs:
      charms: ${{ steps.collect.outputs.charms }}

  build:
    strategy:
      matrix:
        charm: ${{ fromJSON(needs.collect-charms.outputs.charms) }}
    name: ${{ matrix.charm.job_name }}
    needs:
      - collect-charms
    uses: ./.github/workflows/build_charm.yaml
    with:
      github_repository: ${{ matrix.charm.github_repository }}
      ref: ${{ matrix.charm.ref }}
      relative_path_to_charmcraft_yaml: ${{ matrix.charm.relative_path_to_charmcraft_yaml }}
      charm_index: ${{ matrix.charm.charm_index }}
