name: Build & release wheels

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '53 23 * * *'  # Daily at 23:53 UTC
  workflow_dispatch:

jobs:
  build:
    name: Build & release wheels
    runs-on: ubuntu-latest
    steps:
      - name: Install pyenv
        run: |
          sudo apt-get update
          sudo apt-get install build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev curl libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev -y
          curl https://pyenv.run | bash
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up environment
        run: |
          pipx install poetry
          pipx install tox
      - name: Install CLI
        run: pipx install ./cli/
      - name: Build wheels from source
        run: build charms.json
      - name: Create GitHub release
        run: |
          name="build-$(date +%s)-v2"
          gh release create "$name" --title "$name" ~/charmcraftcache-hub-ci/release/*
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write  # Needed to create release